---
backend:
  name: git-gateway
  branch: main
media_folder: static/uploads
public_folder: uploads
publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blog
    folder: docs
    nested:
      depth: 100
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
