backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  # publish_mode: editorial_workflow
media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
publish_mode: editorial_workflow
collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
    nested:
      depth: 2
      summary: "{{title}}"
    meta: { path: { widget: string, label: "Path", index_file: "index" } }
